syntax                     = "Lua51"
column_width               = 160
line_endings               = "Unix"
indent_type                = "Spaces"
indent_width               = 8
quote_style                = "AutoPreferDouble"
call_parentheses           = "Always"
space_after_function_names = "Never"
block_newline_gaps         = "Never"
collapse_simple_statement  = "Never"
